// <auto-generated />
using System;
using CodeStackLMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeStackLMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227010438_AddMustChangePasswordFlag")]
    partial class AddMustChangePasswordFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RubricJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Assignments_DueDate");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_Assignments_ModuleId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Cohort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cohorts_Name");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Cohorts_DateRange");

                    b.ToTable("Cohorts", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.CohortCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_CohortCourses_CourseId");

                    b.HasIndex("CohortId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("IX_CohortCourses_CohortId_CourseId");

                    b.ToTable("CohortCourses", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_Courses_Title");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.FeedbackComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LineEnd")
                        .HasColumnType("int");

                    b.Property<int?>("LineStart")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_FeedbackComments_AuthorId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FeedbackComments_CreatedAt");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_FeedbackComments_SubmissionId");

                    b.HasIndex("SubmissionId", "FilePath")
                        .HasDatabaseName("IX_FeedbackComments_SubmissionId_FilePath");

                    b.ToTable("FeedbackComments", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.GitHubSubmissionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CommitHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepoUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommitHash")
                        .HasDatabaseName("IX_GitHubSubmissionInfos_CommitHash");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_GitHubSubmissionInfos_SubmissionId");

                    b.ToTable("GitHubSubmissionInfos", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OverallComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricBreakdownJson")
                        .IsRequired()
                        .HasColumnType("JSON");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradedAt")
                        .HasDatabaseName("IX_Grades_GradedAt");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("IX_Grades_InstructorId");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Grades_SubmissionId");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("LinkDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoBlobPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VideoMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoSource")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("IX_Lessons_ModuleId");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Lessons_Type");

                    b.HasIndex("ModuleId", "Order")
                        .HasDatabaseName("IX_Lessons_ModuleId_Order");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_Modules_CourseId");

                    b.HasIndex("CourseId", "Order")
                        .HasDatabaseName("IX_Modules_CourseId_Order");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("IX_Submissions_AssignmentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Submissions_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Submissions_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Submissions_StudentId");

                    b.HasIndex("AssignmentId", "StudentId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Submissions_AssignmentId_StudentId_AttemptNumber");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.SubmissionArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlobPath")
                        .HasDatabaseName("IX_SubmissionArtifacts_BlobPath");

                    b.HasIndex("Checksum")
                        .HasDatabaseName("IX_SubmissionArtifacts_Checksum");

                    b.HasIndex("SubmissionId")
                        .HasDatabaseName("IX_SubmissionArtifacts_SubmissionId");

                    b.ToTable("SubmissionArtifacts", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Users_IsActive");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Assignment", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Module", "Module")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.CohortCourse", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Cohort", "Cohort")
                        .WithMany("CohortCourses")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeStackLMS.Domain.Entities.Course", "Course")
                        .WithMany("CohortCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.FeedbackComment", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.User", "Author")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeStackLMS.Domain.Entities.Submission", "Submission")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.GitHubSubmissionInfo", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Submission", "Submission")
                        .WithOne("GitHubInfo")
                        .HasForeignKey("CodeStackLMS.Domain.Entities.GitHubSubmissionInfo", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Grade", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.User", "Instructor")
                        .WithMany("GradesGiven")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeStackLMS.Domain.Entities.Submission", "Submission")
                        .WithOne("Grade")
                        .HasForeignKey("CodeStackLMS.Domain.Entities.Grade", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Module", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Submission", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeStackLMS.Domain.Entities.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.SubmissionArtifact", b =>
                {
                    b.HasOne("CodeStackLMS.Domain.Entities.Submission", "Submission")
                        .WithMany("Artifacts")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Cohort", b =>
                {
                    b.Navigation("CohortCourses");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Course", b =>
                {
                    b.Navigation("CohortCourses");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Module", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("FeedbackComments");

                    b.Navigation("GitHubInfo");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("CodeStackLMS.Domain.Entities.User", b =>
                {
                    b.Navigation("FeedbackComments");

                    b.Navigation("GradesGiven");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
